argo-cd:
  crds:
    install: true
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: true
  configs:
    params:
      server.insecure: true
  server:
    service:
      type: ClusterIP
