apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsets
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: git@github.com:michaelbrister/argo-cd.git
    targetRevision: HEAD
    path: platform/appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
